
# Copyright (c) 2024-2026 embed-dsp, All Rights Reserved.
# Author: Gudmundur Bogason <gb@embed-dsp.com>


MD := header.md

# Version 1: 79acd05

# Version 2: 3776576
# MD += tool_digital.md
# MD += tool_fpga.md
# MD += tool_esl.md
# MD += tool_analog.md
# MD += tool_pcb.md
# MD += tool_dsp.md
# MD += tool_sw.md
# MD += tool_fw.md
# MD += lib_sw.md
# MD += linux.md
# MD += guide.md

# Version 3: ...
MD += nvidia.md
MD += tool_digital.md
MD += tool_fpga.md
MD += tool_esl.md
MD += tool_analog.md
MD += tool_pcb.md
MD += tool_dsp.md
MD += tool_sw.md
MD += tool_fw.md
MD += lib_sw.md
MD += linux.md
MD += guide.md

all:
	@cat $(MD) > README.md
